export const data = {
  products: [
    {
      id: '1',
      name: 'Pink Polo Shirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      id: '2',
      name: 'Marl Polo Shirt',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '3',
      name: 'Slim Fit Polo Shirt',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: 'Orange Polo Shirt',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '5',
      name: '핑크핑크티',
      image: '/images/p1.jpg',
      price: 70,
      countInStock: 5,
      rating: 4.5,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      id: '6',
      name: '파랑파랑티',
      image: '/images/p2.jpg',
      price: 95,
      countInStock: 5,
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      id: '7',
      name: '더파랑파랑티',
      image: '/images/p3.jpg',
      price: 40,
      countInStock: 5,
      rating: 4.5,
      numReviews: 4,
      description: 'high quality product',
    },
    {
      id: '8',
      name: '주황주황티',
      image: '/images/p4.jpg',
      price: 85,
      countInStock: 5,
      rating: 4.5,
      numReviews: 13,
      description: 'high quality product',
    },
  ],
}
